# Redactify Configuration File
# Place in the ROOT directory (e.g., /home/stark007/Projects/Redactify/)
# Settings here override defaults in Redactify/core/config.py

# ====================================================================
# PRESIDIO NLP CONFIGURATION - Text Analysis & PII Recognition Settings
# ====================================================================
presidio_config:
  nlp_config:
    nlp_engine_name: spacy
    models: [{ "lang_code": "en", "model_name": "en_core_web_trf" }] # Transformer model (high accuracy)
    # Alternative options: en_core_web_lg (large), en_core_web_md (medium), en_core_web_sm (small), en_core_web_trf
    # Labels to ignore in the NER model output
    labels_to_ignore: ["FAC", "ORG"]
    allow_all_entity_types: true # Allow all entity types to be considered for recognition
  supported_languages: ["en"]
  # Add name context words to enhance recognition
  context_words:
    PERSON: ["name", "person", "mr", "mrs", "ms", "dr", "prof"]

# ====================================================================
# FILE STORAGE CONFIGURATION
# ====================================================================
# Directory paths
temp_dir: temp_files
upload_dir: upload_files

# File lifecycle
temp_file_max_age_seconds: 172800 # Keep temp files for 2 days

# File size limits
max_file_size_mb: 100 # Maximum upload file size in megabytes

# ====================================================================
# PROCESSING & ANALYSIS CONFIGURATION
# ====================================================================
# PII Detection thresholds
ocr_confidence_threshold: 0.1 # Lower threshold means more text will be detected (may include false positives)
presidio_confidence_threshold: 0.05 # Lowered for better detection of names (especially all caps)

# Service URLs
# For local development:
# redis_url: redis://localhost:6379/0
# For Docker:
redis_url: redis://redis:6379/0 # Redis connection for Celery tasks

# ====================================================================
# TASK PROCESSING CONFIGURATION
# ====================================================================
# Celery task timeouts
celery_task_soft_time_limit: 600 # 10 minutes - worker receives timeout signal
celery_task_hard_time_limit: 660 # 11 minutes - forceful termination

# ====================================================================
# WEB SERVER CONFIGURATION
# ====================================================================
# Web server settings - Docker needs host 0.0.0.0 to access from outside container
host: 0.0.0.0 # Listen on all interfaces (required for Docker)
port: 5000

# ====================================================================
# LOGGING CONFIGURATION
# ====================================================================
# Enable logging for text extraction
log_level: INFO # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
